# Generated by Django 5.2.5 on 2025-08-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Ism")),
                ("last_name", models.CharField(max_length=50, verbose_name="Familiya")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Telefon raqami"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email manzil"),
                ),
                ("message", models.TextField(verbose_name="Yuborilgan xabar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Xabar",
                "verbose_name_plural": "Xabarlar",
                "ordering": ["-created_at"],
            },
        ),
    ]
